### PR TITLE
Initial mockup implementation

### PR DESCRIPTION
**Pull request by acciochris**
Link to mockup: https://drive.google.com/file/d/1kb5gEThnoZ9vhDcMtKMT1BV3E4TbyxLc/view

### CODE REVIEW

**Comment by acciochris** [comment]
We are planning to use chart.js to render the updated graphs instead of embedding static images.

**Comment by anish-lakkapragada** [comment]
@acciochris I've added changes using solid-chart-js library to the anish branch.

**Review by acciochris — COMMENTED** [review]
Also please no force pushes. Pull and rebase instead.

**Comment by acciochris** [comment]
guys, please don't force push, pull and rebase. This overrides my commits.

**Pull request merged**
